name: documentation

on:
  workflow_dispatch:
  push:
    branches: [master, main]
    paths: ['README.md']

env:
  DOCKER_HUB_IMAGE_NAME: skipero/neat-ci

jobs:
  docker-hub-description:
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peter-evans/dockerhub-description@v3 # Action page: <https://github.com/peter-evans/dockerhub-description>
        with:
          username: ${{ vars.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ env.DOCKER_HUB_IMAGE_NAME }}
